### ISSUE TITLE
Contradiction and Ambiguity clause clause 

### ISSUE THREAD

**Issue by AngusP** [compsoc-edinburgh/constitution#3]
Given some parts of the constitution are a bit ambiguous, or seem to contradict other parts of the constitution or other regulations that apply to the society, the way these conflicts are resolved should be explicitly stated

**Comment by qaisjp** [comment]
@Alarian54 We should probably bring this up at the next meeting. Please don't let us forget :)

**Comment by Alarian54** [comment]
Which parts in particular? Could they be noted here or shall we just look through the constitution then?

**Comment by qaisjp** [comment]
We can note them here. Procedure for what to do when confronted with a conflicting situation should be discussed and added to the Constitution, though.

**Comment by Alarian54** [comment]
Okay, firstly I'm assuming that there's no need to be super pernickety about grammar and punctuation -
 e.g. how come some of the bullet points have full stops but others don't?
So it seems some of the following is relevant:
1. "Free freebies", "indulgence of all geekery" and "Most Excellent" seem pretty vague -  or is that the point?
2. What happens if we discover we're less than 75% Edinburgh University students, or a non-student wants to join but we're at exactly 75%? Are they kicked out, or prevented from joining?
3.  Recent committee discussions (e.g. Do School of Informatics reps get a vote each, or two if they're also in the committee?) should be added
4. What happens if the committee "decides to dis-associate CompSoc from a SIG"? Does the SIG become a separate society? What happens to the links between it and CompSoc - e.g. shared membership?
4. What happens if the membership quorum of an AGM is not met? Is the AGM prevented from taking place?
4. Currently, the Constitution only mentions amending it at AGMs or EGMs. Is amendment possible at other times - regular meetings, for example?

**Comment by qaisjp** [comment]
1. .
2. Good point. we should be explicit on preventing non University of Edinburgh students from joining if we would go below 75%.
3. #4 is there to emphasise that "their" vote is actually the school's vote.
4. To discuss
5. To discuss
6. Nope. Only at AGMs. We should probably explicitly mention this, EUSA mandates something official.
